Fiap.Web.AspNet5/Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;
using Fiap.Web.AspNet5.Data;
using Fiap.Web.AspNet5.Models;
using Fiap.Web.AspNet5.Repository;
using Fiap.Web.AspNet5.Controllers.Filters;

namespace Fiap.Web.AspNet5.Controllers
{
    [FiapAuthFilter]
    public class FornecedorController : Controller
    {
        private readonly FornecedorRepository fornecedorRepository;

        public FornecedorController(DataContext context)
        {
            fornecedorRepository = new FornecedorRepository(context);
        }

        // GET: Fornecedor
        public IActionResult Index()
        {

            var lista = fornecedorRepository.FindAll();
            
            /*
            return lista != null ? 
                          View(lista) :
                          Problem("Entity set 'DataContext.Fornecedores'  is null.");
            */

            return View(lista);
        }

        // GET: Fornecedor/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedorModel = fornecedorRepository.FindById((int)id);

            if (fornecedorModel == null)
            {
                return NotFound();
            }

            return View(fornecedorModel);
        }

        // GET: Fornecedor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fornecedor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FornecedorModel fornecedorModel)
        {
            if (ModelState.IsValid)
            {
                fornecedorRepository.Insert(fornecedorModel);

                return RedirectToAction(nameof(Index));
            }
            return View(fornecedorModel);
        }

        // GET: Fornecedor/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedorModel = fornecedorRepository.FindById((int)id);

            if (fornecedorModel == null)
            {
                return NotFound();
            }
            return View(fornecedorModel);
        }

        // POST: Fornecedor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, FornecedorModel fornecedorModel)
        {
            if (id != fornecedorModel.FornecedorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                fornecedorRepository.Update(fornecedorModel);
                
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedorModel);
        }

        // GET: Fornecedor/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedorModel = fornecedorRepository.FindById((int)id);

            if (fornecedorModel == null)
            {
                return NotFound();
            }

            return View(fornecedorModel);
        }

        // POST: Fornecedor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {

            if (id == null)
            {
                return Problem("Entity set 'DataContext.Fornecedores'  is null.");
            }

            var fornecedorModel = fornecedorRepository.FindById((int)id);

            if (fornecedorModel != null)
            {
                fornecedorRepository.Delete(fornecedorModel);
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

Fiap.Web.AspNet5/Controllers/LoginController.cs
using AutoMapper;
using Fiap.Web.AspNet5.Models;
using Fiap.Web.AspNet5.Repository.Interface;
using Fiap.Web.AspNet5.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;

namespace Fiap.Web.AspNet5.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsuarioRepository usuariosRepository;
        private readonly IMapper mapper;

        public LoginController(IUsuarioRepository _usuariosRepository, IMapper _mapper)
        {
            this.usuariosRepository = _usuariosRepository;
            this.mapper = _mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login(LoginViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                /*
                var usuario = new UsuarioModel();
                usuario.UsuarioSenha = loginViewModel.UsuarioSenha;
                usuario.UsuarioEmail = loginViewModel.UsuarioEmail;
                */

                var usuario = mapper.Map<UsuarioModel>(loginViewModel);
                var usuarioLogado = usuariosRepository.Login(usuario);

                if (usuarioLogado == null || usuarioLogado.UsuarioId == 0)
                {
                    ViewBag.ErrorMessage = "Login ou Senha invalida!";
                    return View(nameof(Index));
                }
                else
                {
                   
                    loginViewModel = mapper.Map<LoginViewModel>(usuarioLogado);

                    var vmJson = Newtonsoft.Json.JsonConvert.SerializeObject(loginViewModel);
                    HttpContext.Session.SetString("usuarioLogado", vmJson);
                    return RedirectToAction(nameof(Index), "Home");
                    
                }

            }
            else
            {
                return View(nameof(Index));
            }

        }

        [HttpGet]
        public IActionResult Logoff()
        {
            HttpContext.Session.Clear();
            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

Fiap.Web.AspNet5/Controllers/RepresentanteController.cs
using Microsoft.AspNetCore.Mvc;
using Fiap.Web.AspNet5.Data;
using Fiap.Web.AspNet5.Models;
using Fiap.Web.AspNet5.Repository;
using Fiap.Web.AspNet5.Repository.Interface;
using Fiap.Web.AspNet5.Controllers.Filters;

namespace Fiap.Web.AspNet5.Controllers
{
    [FiapAuthFilter]
    public class RepresentanteController : Controller
    {
        private readonly IRepresentanteRepository representanteRepository;

        public RepresentanteController(IRepresentanteRepository _representanteRepository)
        {
            representanteRepository = _representanteRepository;
        }

        // GET: Representante
        public IActionResult Index()
        {
            var listaRepresentantes = representanteRepository.FindAll();

              return View(listaRepresentantes);
        }

        // GET: Representante/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representanteModel = representanteRepository.FindById((int)id);

            if (representanteModel == null)
            {
                return NotFound();
            }

            return View(representanteModel);
        }

        // GET: Representante/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RepresentanteModel representanteModel)
        {
            if (ModelState.IsValid)
            {
                representanteRepository.Insert(representanteModel);

                return RedirectToAction(nameof(Index));
            }

            return View(representanteModel);
        }

        // GET: Representante/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representanteModel = representanteRepository.FindById((int)id);

            if (representanteModel == null)
            {
                return NotFound();
            }

            return View(representanteModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, RepresentanteModel representanteModel)
        {
            if (id != representanteModel.RepresentanteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                representanteRepository.Update(representanteModel);

                return RedirectToAction(nameof(Index));
            }

            return View(representanteModel);
        }

        // GET: Representante/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representanteModel = representanteRepository.FindById((int)id);

            if (representanteModel == null)
            {
                return NotFound();
            }

            return View(representanteModel);
        }

        // POST: Representante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return Problem("Entity set 'DataContext.Representantes'  is null.");
            }

            var representanteModel = representanteRepository.FindById((int)id);

            if (representanteModel != null)
            {
                representanteRepository.Delete(representanteModel);
            }
            
            return RedirectToAction(nameof(Index));

        }

    }
}

Fiap.Web.AspNet5/Views/Shared/_Layout.cshtml
@using Fiap.Web.AspNet5.ViewModel
@{
    string? emailUsuario = "";
    var usuarioSession = Context.Session.GetString("usuarioLogado");

    if (!string.IsNullOrEmpty(usuarioSession))
    {
        var usuarioLogado = Newtonsoft.Json.JsonConvert.DeserializeObject<LoginViewModel>(usuarioSession);
        emailUsuario = usuarioLogado.UsuarioEmail;
    }
    
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro Usuário</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Web.AspNet5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro de Usuários</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (!string.IsNullOrEmpty(usuarioSession))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Representante" asp-action="Index">Representante</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logoff">Logoff</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @RenderSection("Menu", required: false) 

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fiap.Web.AspNet5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <p> Olá: @emailUsuario</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Fiap.Web.AspNet5/Views/Shared/_LayoutDark.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro Usuário</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Web.AspNet5.styles.css" asp-append-version="true" />
</head>
<body style="background-color: lightgray">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fiap.Web.AspNet5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fiap.Web.AspNet5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>